### ISSUE TITLE
Only release nightly builds when actual changes occurred

### ISSUE THREAD

**Issue by GeertvanHorrik** [OctopusDeploy/OctopusCLI#122]
We use OctopusTools in combination with Cake. We set up dependabot for the cake tools dependencies, and OctopusTools is one of them.

I've noticed that every (week) day, a new build is pushed to NuGet (see https://www.nuget.org/packages/OctopusTools/). However, not all releases have actual new changes (commits).

Every night, dependabot creates a new PR and we need to review the changes before merging, it would be great if you could consider the following rules:

Only deploy when:

1. A change has been made (commits currently available > last deployment date)
2. A new .NET (core) version becomes available (only needed when deploying the fx with the app)

If you need more info, please let me know.

**Comment by matt-richardson** [comment]
Thanks for your feedback @GeertvanHorrik. We build & publish every day to ensure that our pipelines dont suffer "bit rot" - I'm sure you've come across situations where you go to urgently release something after _n_ months have passed, and nothing works.

We modified our [downloads page](https://octopus.com/downloads/octopuscli) so that it doesn't show these, but we've obviously missed your use case here. 

Leave it with us - I'll add a card to ponder how we can handle this better.

In the meantime, you can either use the `ignore` [configuration option](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore) or use `@dependabot ignore this minor version` on the next dependabot PR until you need an update.

Hope that helps!

**Comment by GeertvanHorrik** [comment]
Thanks for taking the time to respond, it's much appreciated. 

I didn't see any new releases so I think it's already solved, thank you very much!
