### ISSUE TITLE
Latest version breaks as it is silently updated to require .NET 3.1

### ISSUE THREAD

**Issue by Bouke** [OctopusDeploy/OctopusCLI#165]
Same issue as 6 months ago: https://github.com/OctopusDeploy/OctopusCLI/issues/141

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      2.1.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.13 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
```

Apparently version 8.0.0 just got released. To revert to the previous version, use the following step in the Azure DevOps pipeline:

```yaml
- task: OctoInstaller@4
  displayName: Install Octo
  inputs:
    version: 7.4.3663
```

I have a few concerns regarding this change:

- Why is this happening again?
- What haven't you learned from the previous time?
- What will you do to prevent this from happening again?

**Comment by johnsimons** [comment]
Hi @Bouke 

Thank you for submitting this issue. We can confirm that this issue is now resolved. Regrettably, our Azure DevOps (ADO) integration with Octopus Deploy was briefly broken following a major update to the Octopus CLI. This occurred as a result of the way dependencies are currently resolved at runtime within the ADO integration itself. We intend to change the nature of this resolution whilst providing more control for customers who use this integration in ADO.

## Background

Recent changes to the Octopus CLI address the support policies associated with .NET and .NET Core; there are numerous versions of .NET and .NET Core that have passed "end of support" dates (#161). These support policies have resulted in downstream changes to dependencies within our ADO integration ([#4871](https://github.com/actions/virtual-environments/issues/4871)).

Our ADO integration was designed to provide a seamless experience for customers by embedding the Octopus CLI. Most notably, this supported customers using our ADO integration with an on-premise instance(s) of Azure DevOps Server where outside Internet access was limited due to security policies. This resulted in a nice side benefit of eliminating the need for an explicit task (i.e. precondition) to download and install the Octopus CLI through the OctoInstaller task. Unfortunately, no solution is perfect; this design has trade-offs. And, as evidenced by this issue, there have been occasions where upstream changes have resulted in downstream consequences.

The Octopus CLI that is embedded with our ADO integration relies on the portable libraries of .NET and .NET Core to perform its work. Unfortunately, this imposes strict runtime resolution constraints for dependencies. If an agent is missing the expected version of .NET or .NET Core then our ADO integration generates a runtime exception. Please note our decision to use the portable libraries of .NET and .NET Core predated self-contained executable support in these technologies.

As stated previously, we made a decision to not require customers to include the OctoInstaller task as a precondition for other tasks. We decided to automatically download the latest version of the Octopus CLI and use that version. This is why the ADO tasks are now downloading the latest version which uses netcore3.1.

## Workaround

The following list of actions can mitigate the current behaviour should an agent encounter a runtime error due to missing framework version:

- Verify that on-premise agents have netcore3.1 installed;
- Use OctoInstaller task as a precondition to ensure a version < 8.0;
- Include the dotnet installer task as a precondition;
  ![image](https://user-images.githubusercontent.com/122651/156460394-a1ffa29f-14ad-4ae3-ab33-56a068e56b7c.png)
  ![image](https://user-images.githubusercontent.com/122651/156460856-2b457f00-596e-4b28-8a99-9d6863d90eb0.png)

## Future Roadmap

It is our intention to release an update of our ADO integration that will resolve the behaviour observed in this issue and provide more control over dependencies to our customers.

First, we plan to make OctoInstaller task a requirement for any tasks; automatic downloading of the Octopus CLI will no longer be supported.

Second, we plan to remove the embedded Octopus CLI; agents without Internet access will be required to download and install the Octopus CLI.

Third, the Octopus CLI downloaded as part of OctoInstaller task will be self-contained, which means no longer depends on .NET frameworks being installed on the agent.
